-- MySQL Script generated by MySQL Workbench
-- Tue 10 Apr 2018 10:44:01 PM CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Yeyland_Wutani
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Yeyland_Wutani
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Yeyland_Wutani` DEFAULT CHARACTER SET utf8 ;
USE `Yeyland_Wutani` ;

-- -----------------------------------------------------
-- Table `Yeyland_Wutani`.`locations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Yeyland_Wutani`.`locations` ;

CREATE TABLE IF NOT EXISTS `Yeyland_Wutani`.`locations` (
  `locationcode` INT NOT NULL,
  `locationname` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NULL,
  UNIQUE INDEX `locID_UNIQUE` (`locationcode` ASC),
  PRIMARY KEY (`locationcode`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Yeyland_Wutani`.`positions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Yeyland_Wutani`.`positions` ;

CREATE TABLE IF NOT EXISTS `Yeyland_Wutani`.`positions` (
  `positioncode` INT NOT NULL,
  `positionname` VARCHAR(45) NOT NULL,
  `description` VARCHAR(90) NULL,
  PRIMARY KEY (`positioncode`),
  UNIQUE INDEX `pID_UNIQUE` (`positioncode` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Yeyland_Wutani`.`departments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Yeyland_Wutani`.`departments` ;

CREATE TABLE IF NOT EXISTS `Yeyland_Wutani`.`departments` (
  `depnum` INT NOT NULL,
  `depname` VARCHAR(45) NOT NULL,
  `description` VARCHAR(90) NULL,
  PRIMARY KEY (`depnum`),
  UNIQUE INDEX `dID_UNIQUE` (`depnum` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Yeyland_Wutani`.`employees`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Yeyland_Wutani`.`employees` ;

CREATE TABLE IF NOT EXISTS `Yeyland_Wutani`.`employees` (
  `eID` INT NOT NULL,
  `lname` VARCHAR(45) NOT NULL,
  `fname` VARCHAR(45) NOT NULL,
  `location_locationcode` INT NOT NULL,
  `positions_positioncode` INT NOT NULL,
  `departments_depnum` INT NOT NULL,
  `address` VARCHAR(45) NULL,
  `phonenum` VARCHAR(16) NULL,
  PRIMARY KEY (`eID`),
  UNIQUE INDEX `eID_UNIQUE` (`eID` ASC),
  INDEX `fk_employee_location1_idx` (`location_locationcode` ASC),
  INDEX `fk_employees_positions1_idx` (`positions_positioncode` ASC),
  INDEX `fk_employees_departments1_idx` (`departments_depnum` ASC),
  CONSTRAINT `fk_employee_location1`
    FOREIGN KEY (`location_locationcode`)
    REFERENCES `Yeyland_Wutani`.`locations` (`locationcode`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employees_positions1`
    FOREIGN KEY (`positions_positioncode`)
    REFERENCES `Yeyland_Wutani`.`positions` (`positioncode`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employees_departments1`
    FOREIGN KEY (`departments_depnum`)
    REFERENCES `Yeyland_Wutani`.`departments` (`depnum`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Yeyland_Wutani`.`courses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Yeyland_Wutani`.`courses` ;

CREATE TABLE IF NOT EXISTS `Yeyland_Wutani`.`courses` (
  `courseID` INT NOT NULL,
  `coursename` VARCHAR(45) NOT NULL,
  `description` VARCHAR(90) NULL,
  PRIMARY KEY (`courseID`),
  UNIQUE INDEX `cID_UNIQUE` (`courseID` ASC)
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Yeyland_Wutani`.`events`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Yeyland_Wutani`.`events` ;

CREATE TABLE IF NOT EXISTS `Yeyland_Wutani`.`events` (
  `event` INT NOT NULL,
  `date` DATE NOT NULL,
  `employees_eID` INT NOT NULL,
  `courses_courseID` INT NOT NULL,
  `location_locationcode` INT NOT NULL,
  PRIMARY KEY (`event`),
  INDEX `fk_course_event_employees1_idx` (`employees_eID` ASC),
  INDEX `fk_events_courses1_idx` (`courses_courseID` ASC),
  INDEX `fk_events_locatio_idx` (`location_locationcode` ASC),
  CONSTRAINT `fk_course_event_employees1`
    FOREIGN KEY (`employees_eID`)
    REFERENCES `Yeyland_Wutani`.`employees` (`eID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_events_courses1`
    FOREIGN KEY (`courses_courseID`)
    REFERENCES `Yeyland_Wutani`.`courses` (`courseID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_events_location`
    FOREIGN KEY (`location_locationcode`)
    REFERENCES `Yeyland_Wutani`.`locations` (`locationcode`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Yeyland_Wutani`.`course_attendance`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Yeyland_Wutani`.`course_attendance` ;

CREATE TABLE IF NOT EXISTS `Yeyland_Wutani`.`course_attendance` (
  `events_event` INT NOT NULL,
  `employees_eID` INT NOT NULL,
  INDEX `fk_course_attendance_events1_idx` (`events_event` ASC),
  INDEX `fk_course_attendance_employees1_idx` (`employees_eID` ASC),
  CONSTRAINT `fk_course_attendance_events1`
    FOREIGN KEY (`events_event`)
    REFERENCES `Yeyland_Wutani`.`events` (`event`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_course_attendance_employees1`
    FOREIGN KEY (`employees_eID`)
    REFERENCES `Yeyland_Wutani`.`employees` (`eID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
